### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by p1k0pan** [ayamir/goblocks#1]
我按照设置运行出现一下错误
![Screenshot_20211002_170620](https://user-images.githubusercontent.com/36180022/135710226-c2f2e8a0-56cf-449e-836c-26fa9540b215.png)

请问如何解决

**Comment by ayamir** [comment]
你的`config.toml`文件是正常的吗？

**Comment by p1k0pan** [comment]
应该没有问题的，克隆下来就改了下网络名称
```
[networks]
wlan = "wlan0"
lan = "lo"

[color]
# background or foreground
style = "background"

netColor = "#d08070"
cpuColor = "#ebcb8b"
memColor = "#a3be8c"
volColor = "#5e81ac"
batColor = "#88c0d0"
datColor = "#b48ead"
```

**Comment by ayamir** [comment]
我用你的`config.toml`没有问题，可能是`go-toml`这个库问题
```shell
cd 你clone的路径
go mod tidy
go build .
goblocks &
```

**Comment by p1k0pan** [comment]
还是不行
![Screenshot_20211003_110111](https://user-images.githubusercontent.com/36180022/135737898-3b9d51fc-0b71-4688-b334-6262cde44b55.png)

**Comment by ayamir** [comment]
先pull然后删掉这一行：
https://github.com/ayamir/goblocks/blob/6b10bc2f8d57a08fb6a60fa5ba9e3f8dd50e8828/goblocks.go#L48
之后`go build .`应该就可以了

**Comment by p1k0pan** [comment]
没问题了，十分感谢！
